global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "alert.rules.yml"

scrape_configs:

  # Main infrastructure Node Exporter
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - node-exporter:9100

  # Simulated App, DB and Monitoring servers
  - job_name: "enterprise-servers"
    static_configs:
      - targets:
          - app-server:9100
          - db-server:9100
          - monitoring-server:9100

  # Blackbox monitoring for Apache Web Server
  - job_name: "blackbox-http"
    metrics_path: /probe
    params:
      module:
        - http_2xx

    static_configs:
      - targets:
          - http://web-server:80

    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target

      - source_labels:
          - __param_target
        target_label: instance

      - target_label: __address__
        replacement: blackbox-exporter:9115
