services:
  flask:
    build:
      context: ../flask
    image: flask-alert-middleware:v1
    container_name: flask-container
    ports:
      - "5001:5000"
    env_file:
      - ../flask/.env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      incident-net:
        ipv4_address: 172.30.0.10
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus-container
    ports:
      - "9091:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - incident-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana-container
    ports:
      - "3001:3000"
    networks:
      - incident-net
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager-container
    ports:
      - "9095:9093"
    volumes:
      - ../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - incident-net
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter-container
    ports:
      - "9101:9100"
    networks:
      - incident-net
    restart: unless-stopped

  osticket-db:
    image: mariadb:10.6
    container_name: osticket-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticketpassword
    volumes:
      - osticket-db-data:/var/lib/mysql
    networks:
      - incident-net
    restart: unless-stopped

  osticket:
    image: campbellsoftwaresolutions/osticket
    container_name: osticket-container
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: osticket-db
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: osticketpassword
    depends_on:
      - osticket-db
    networks:
      - incident-net
    restart: unless-stopped

volumes:
  osticket-db-data:

networks:
  incident-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
