from flask import Flask, request, jsonify
import requests
import json
from dotenv import load_dotenv
import os

# ADDED: import test email function from separate email service file
from email_service import send_email, SUPPORT_EMAILS, CLIENT_EMAILS, SUPPORT_PHONE, SERVICE_NAME, ENVIRONMENT

load_dotenv()

app = Flask(__name__)

# osTicket configuration
OSTICKET_URL = os.getenv("OSTICKET_URL")
API_KEY = os.getenv("API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SOURCE_IP = os.getenv("SOURCE_IP")


@app.route('/webhook', methods=['POST'])
def webhook():

    data = request.json

    print("========== ALERT RECEIVED ==========")
    print(json.dumps(data, indent=4))

    try:
        if 'alerts' in data:
            alert = data['alerts'][0]

            alert_name = alert.get('labels', {}).get('alertname', 'Unknown Alert')
            server = alert.get('labels', {}).get('instance', 'Unknown Server')
            severity = alert.get('labels', {}).get('severity', 'warning')
            status = alert.get('status', 'firing')
        else:
            alert_name = data.get('title', 'Datasource Alert')
            server = "Grafana"
            severity = "critical"
            status = data.get('status', 'firing')

        print(f"Alert Name: {alert_name}")
        print(f"Server: {server}")
        print(f"Severity: {severity}")
        print(f"Status: {status}")

        if status == "resolved":
            print("Resolved alert ignored")
            return jsonify({"status": "resolved ignored"}), 200

        subject = f"[{severity.upper()}] {alert_name}"

        message = f"""
INCIDENT CREATED AUTOMATICALLY

Alert Name : {alert_name}
Server     : {server}
Severity   : {severity.upper()}
Status     : {status.upper()}

Description:
Infrastructure alert triggered from Prometheus/Alertmanager.

Recommended Actions:
1. Check node-exporter container status.
2. Verify Prometheus target health.
3. Check server CPU, Memory and Disk.
4. Review container logs.
5. Restart affected service if required.

Generated By:
Enterprise Incident Management Platform
Prometheus | Alertmanager | Flask | osTicket
"""

        payload = {
            "name": "Monitoring Automation",
            "email": SENDER_EMAIL,
            "phone": "0000000000",
            "subject": subject,
            "message": message,
            "ip": SOURCE_IP,
            "topicId": 1
        }

        headers = {
            "X-API-Key": API_KEY,
            "Content-Type": "application/json"
        }

        response = requests.post(
            OSTICKET_URL,
            headers=headers,
            data=json.dumps(payload)
        )

        print("Ticket Response:", response.text)

        ticket_number = response.text.strip()
        priority = alert.get('labels', {}).get('priority', 'P3')
        summary = alert.get('annotations', {}).get('summary', 'No summary')
        description = alert.get('annotations', {}).get('description', 'No description')
        start_time = alert.get('startsAt', 'Unknown')

        support_subject = f"[{priority}][{severity.upper()}][{ticket_number}] {alert_name} | {server} | Immediate Action Required"

        support_body = f"""
Dear Support Team,

A new incident has been automatically created.

Incident Number : {ticket_number}
Priority        : {priority}
Severity        : {severity.upper()}
Alert Name      : {alert_name}
Server          : {server}
Service         : {SERVICE_NAME}
Environment     : {ENVIRONMENT}
Status          : {status.upper()}
Triggered At    : {start_time}

Summary:
{summary}

Description:
{description}

Recommended Actions:
1. Verify node-exporter container.
2. Check Docker status.
3. Review Prometheus target health.
4. Review application logs.
5. Restart service if required.

Support Contact:
Email : {SUPPORT_EMAILS[0]}
Phone : {SUPPORT_PHONE}

Generated Automatically,
Enterprise Incident Management Platform
"""

        client_subject = f"[{ticket_number}][{severity.upper()}] Incident Created - {SERVICE_NAME}"

        client_body = f"""
Dear Customer,

An infrastructure incident has been detected.

Our monitoring platform has automatically created an incident and our engineering team has started investigating.

Incident Number : {ticket_number}
Severity        : {severity.upper()}
Affected Service: {SERVICE_NAME}
Detected At     : {start_time}
Current Status  : Investigation In Progress

There is no action required from your side at this time.

For urgent assistance:
Email : {SUPPORT_EMAILS[0]}
Phone : {SUPPORT_PHONE}

Regards,
Operations Team
"""

        send_email(SUPPORT_EMAILS, support_subject, support_body)
        send_email(CLIENT_EMAILS, client_subject, client_body)

        print("Incident email sent to support and client teams")

    except Exception as e:
        print("Error:", e)

    return jsonify({"status": "success"}), 200


# ADDED: temporary endpoint to test Gmail SMTP before connecting email to incidents
@app.route('/test-email')
def test_email():
    try:
        send_test_email()
        return "Test email sent successfully."
    except Exception as e:
        return f"Error: {e}"


@app.route('/')
def home():
    return "Flask Alert Middleware Running"


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)