from datetime import datetime
from flask import Flask, request, jsonify, render_template
import requests
import json
from dotenv import load_dotenv
import os

from email_service import (
    send_email,
    SUPPORT_EMAILS,
    CLIENT_EMAILS,
    SUPPORT_PHONE,
    SERVICE_NAME,
    ENVIRONMENT
)

from decision_engine import (
    is_duplicate,
    register_incident,
    update_duplicate,
    close_incident
)

load_dotenv()

app = Flask(__name__)

OSTICKET_URL = os.getenv("OSTICKET_URL")
API_KEY = os.getenv("API_KEY")
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
SOURCE_IP = os.getenv("SOURCE_IP")


@app.route('/webhook', methods=['POST'])
def webhook():
    data = request.json

    print("========== ALERT RECEIVED ==========")
    print(json.dumps(data, indent=4))

    try:
        if 'alerts' in data:
            alert = data['alerts'][0]

            alert_name = alert.get('labels', {}).get('alertname', 'Unknown Alert')
            server = alert.get('labels', {}).get('instance', 'Unknown Server')
            severity = alert.get('labels', {}).get('severity', 'warning')
            priority = alert.get('labels', {}).get('priority', 'P3')
            status = alert.get('status', 'firing')
            summary = alert.get('annotations', {}).get('summary', 'No summary')
            description = alert.get('annotations', {}).get('description', 'No description')
            start_time = alert.get('startsAt', 'Unknown')

        else:
            alert_name = data.get('title', 'Datasource Alert')
            server = "Grafana"
            severity = "critical"
            priority = "P1"
            status = data.get('status', 'firing')
            summary = "Grafana datasource alert"
            description = "Grafana datasource alert triggered"
            start_time = "Unknown"

        print(f"Alert Name: {alert_name}")
        print(f"Server: {server}")
        print(f"Severity: {severity}")
        print(f"Priority: {priority}")
        print(f"Status: {status}")

        if status == "resolved":
            close_incident(alert_name, server)
            print(f"Incident closed in Decision Engine: {alert_name} | {server}")

            return jsonify({
                "status": "resolved ignored"
            }), 200

        if is_duplicate(alert_name, server):
            existing = update_duplicate(alert_name, server)

            print("===================================")
            print("Duplicate Incident Detected")
            print(f"Existing Ticket : {existing['ticket_number']}")
            print(f"Occurrences     : {existing['occurrence_count']}")
            print(f"Last Seen       : {existing['last_seen']}")
            print("===================================")

            return jsonify({
                "status": "duplicate ignored",
                "existing_ticket": existing["ticket_number"],
                "occurrences": existing["occurrence_count"]
            }), 200

        subject = f"[{severity.upper()}] {alert_name}"

        message = f"""
INCIDENT CREATED AUTOMATICALLY

Alert Name : {alert_name}
Server     : {server}
Severity   : {severity.upper()}
Priority   : {priority}
Status     : {status.upper()}

Summary:
{summary}

Description:
{description}

Recommended Actions:
1. Check node-exporter container status.
2. Verify Prometheus target health.
3. Check server CPU, Memory and Disk.
4. Review container logs.
5. Restart affected service if required.

Generated By:
Enterprise Incident Management Platform
Prometheus | Alertmanager | Flask | osTicket
"""

        payload = {
            "name": "Monitoring Automation",
            "email": SENDER_EMAIL,
            "phone": "0000000000",
            "subject": subject,
            "message": message,
            "ip": SOURCE_IP,
            "topicId": 1
        }

        headers = {
            "X-API-Key": API_KEY,
            "Content-Type": "application/json"
        }

        response = requests.post(
            OSTICKET_URL,
            headers=headers,
            data=json.dumps(payload)
        )

        print("Ticket Response:", response.text)

        ticket_number = response.text.strip()

        register_incident(
            alert_name,
            server,
            ticket_number,
            severity,
            priority
        )

        print(f"Incident registered in Decision Engine: {ticket_number}")

        support_subject = f"[{priority}][{severity.upper()}][{ticket_number}] {alert_name} | {server} | Immediate Action Required"

        support_body = f"""
Dear Support Team,

A new incident has been automatically created.

Incident Number : {ticket_number}
Priority        : {priority}
Severity        : {severity.upper()}
Alert Name      : {alert_name}
Server          : {server}
Service         : {SERVICE_NAME}
Environment     : {ENVIRONMENT}
Status          : {status.upper()}
Triggered At    : {start_time}

Summary:
{summary}

Description:
{description}

Recommended Actions:
1. Verify node-exporter container.
2. Check Docker status.
3. Review Prometheus target health.
4. Review application logs.
5. Restart service if required.

Support Contact:
Email : {SUPPORT_EMAILS[0]}
Phone : {SUPPORT_PHONE}

Generated Automatically,
Enterprise Incident Management Platform
"""
        generated_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        client_subject = f"[{ticket_number}][{severity.upper()}] Incident Created - {SERVICE_NAME}"

        client_body = f"""
Dear Customer,

An infrastructure incident has been detected.

Our monitoring platform has automatically created an incident and our engineering team has started investigating.

Incident Number : {ticket_number}
Severity        : {severity.upper()}
Alert Name      : {alert_name}
Server          : {server}
Affected Service: {SERVICE_NAME}
Environment     : {ENVIRONMENT}
Detected At     : {start_time}
Generated At    : {generated_time}
Current Status  : Investigation In Progress

There is no action required from your side at this time.

For urgent assistance:
Email : {SUPPORT_EMAILS[0]}
Phone : {SUPPORT_PHONE}

Regards,
Operations Team
"""

        send_email(SUPPORT_EMAILS, support_subject, support_body)
        send_email(CLIENT_EMAILS, client_subject, client_body)

        print("Incident email sent to support and client teams")

    except Exception as e:
        print("Error:", e)

    return jsonify({"status": "success"}), 200

@app.route('/dashboard')
def dashboard():
    return render_template('dashboard.html')


@app.route('/')
def home():
    return "Flask Alert Middleware Running"


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)